name: e2e-on-pr-validation
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

env:
  E2E_LABEL: e2e-tests/ok-to-merge

jobs:
  validate-e2e-labels:
    name: Check e2e labels
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          any_of: ${{ env.E2E_LABEL}}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
